name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    #- name: Build the Docker image
    #  run: sudo docker build . --file Dockerfile --tag poetry-${GITHUB_SHA}
    - name: Run the Poetry app
      run: sudo docker run -d -p 8793:8793 poetry-test2

