name: Docker Image CI #Workflow Name

on:
  push:
    branches: [ "main" ]  # When pushing to main branch then run this action
  
jobs:

  push-image-to-docker-hub:  #Job Name

    runs-on: self-hosted  #The runner i configured in my laptop. So these actions will run in my laptop which is ubuntu

    steps:
    - uses: actions/checkout@v2   #checkout the code
#-----------------------------------------------------------------------------------------------------#    
#### Not working as per https://github.com/docker/login-action/issues/29  - 
####@kushthedude Secrets are not passed to the runner when a workflow is triggered from a forked repository. so i am not able to login 
#### into the dockerhub as it compains "Username and password required"
#    - name: Login to DockerHub
#      uses: docker/login-action@v1
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}

#    - name: Build and push
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        push: true
#        tags: $DOCKER_USER/fuzzy:latest
#---------------------------------------------------------------------------------------------------#

#### because of the above error Just building in the same server and running the app
    - name: Build the Docker image
      run: sudo docker build . --file Dockerfile --tag poetry-${GITHUB_SHA}
    - name: Run the Poetry app
      run: sudo docker run -d -p 8793:8793 poetry-${GITHUB_SHA}

